/* sormula - Simple object relational mapping
 * Copyright (C) 2011-2012 Jeff Miller
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.sormula.tests.active.builder;

import javax.sql.DataSource;

import org.sormula.Database;
import org.sormula.active.ActiveDatabase;
import org.sormula.tests.active.ActiveDatabaseTest;
import org.testng.annotations.Test;


/**
 * Tests for {@link Database}.
 * 
 * @author Jeff Miller
 */
@Test(singleThreaded=true, groups="builder.database")
public class ActiveDatabaseBuilderTest extends ActiveDatabaseTest<BuilderTestRowAR>
{
    String schema = "SomeSchema";
    String dataSourceName = "SomeDataSource";
    

    @Test
    public void builderDataSourceName() throws Exception
    {
        openDatabase(dataSourceName); // creates data source with name
        
        ActiveDatabase activeDatabase = ActiveDatabase.builder(dataSourceName).build();
        assert activeDatabase.getDataSourceName().equals(dataSourceName) : "data source name is incorrect";
        
        activeDatabase = ActiveDatabase.builder(dataSourceName).schema(schema).build();
        assert activeDatabase.getSchema().equals(schema) : "schema name is incorrect";
        
        closeDatabase();
    }


    @Test
    public void builderDataSource() throws Exception
    {
        openDatabase(); // creates test data source
        DataSource dataSource = getDataSource();
        
        ActiveDatabase activeDatabase = ActiveDatabase.builder(dataSource).build();
        assert activeDatabase.getDataSource() == dataSource : "data source is incorrect";
        
        activeDatabase = ActiveDatabase.builder(dataSource).schema(schema).build();
        assert activeDatabase.getSchema().equals(schema) : "schema name is incorrect";
        
        closeDatabase();
    }
    
    
    @Test
    public void builder() throws Exception
    {
        openDatabase(dataSourceName); // creates data source with name
        
        ActiveDatabase activeDatabase = ActiveDatabase.builder(dataSourceName).build();
        assert activeDatabase.isAutoGeneratedKeys() : "autoGeneratedKeys should be true by default";
        
        activeDatabase = ActiveDatabase.builder(dataSourceName).autoGeneratedKeys(false).build();
        assert !activeDatabase.isAutoGeneratedKeys() : "autoGeneratedKeys should be false";
        
        activeDatabase = ActiveDatabase.builder(dataSourceName).build();
        assert !activeDatabase.isReadOnly() : "readOnly should be false by default";
        
        activeDatabase = ActiveDatabase.builder(dataSourceName).readOnly(true).build();
        assert activeDatabase.isReadOnly() : "readOnly should be true";
        
        activeDatabase = ActiveDatabase.builder(dataSourceName).build();
        assert !activeDatabase.isTimings() : "timings should be false by default";
        
        activeDatabase = ActiveDatabase.builder(dataSourceName).timings(true).build();
        assert activeDatabase.isTimings() : "timings should be true";
        
        closeDatabase();
    }
}
