/* sormula - Simple object relational mapping
 * Copyright (C) 2011-2020 Jeff Miller
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.sormula.builder;

import org.sormula.Database;
import org.sormula.SormulaException;
import org.sormula.Table;


/**
 * Base class for {@link Table} builders.
 * 
 * @since 4.4
 * @author Jeff Miller
 *
 * @param <R> type of row objects
 * @param <B> type of builder returned from setter methods
 * @param <T> type of table returned from {@link #build()}
 */
public abstract class AbstractTableBuilder<R, B extends AbstractTableBuilder, T extends Table<R>>
{
    Database database;
    Class<R> rowClass;
    boolean autoGeneratedKeys;
    boolean readOnly;
    String[] requiredCascades;
    String tableName;
    
    
    /**
     * Constructs for a database and row class.
     * 
     * @param database database for table
     * @param rowClass class associated with table
     */
    public AbstractTableBuilder(Database database, Class<R> rowClass)
    {
        this.database = database;
        this.rowClass = rowClass;
        
        // defaults based upon database setting
        autoGeneratedKeys = database.isAutoGeneratedKeys();
    }

    
    /**
     * Builds a {@link Table} instance based upon the properties of this builder.
     * 
     * @return a table instance
     * @throws SormulaException if error
     */
    public abstract T build() throws SormulaException;
    
    
    /**
     * {@inheritDoc}
     */
    protected void init(T table)
    {
        table.setAutoGeneratedKeys(autoGeneratedKeys);
        table.setReadOnly(readOnly);
        if (requiredCascades != null) table.setRequiredCascades(requiredCascades);
        if (tableName != null) table.setTableName(tableName);
    }
    
    
    /**
     * @param autoGeneratedKeys see {@link Table}
     * @return this
     */
    @SuppressWarnings("unchecked")
    public B autoGeneratedKeys(boolean autoGeneratedKeys)
    {
        this.autoGeneratedKeys = autoGeneratedKeys;
        return (B)this;
    }
    
    
    /**
     * @param readOnly see {@link Table}
     * @return this
     */
    @SuppressWarnings("unchecked")
    public B readOnly(boolean readOnly)
    {
        this.readOnly = readOnly;
        return (B)this;
    }
    
    
    /**
     * @param requiredCascades see {@link Table}
     * @return this
     */
    @SuppressWarnings("unchecked")
    public B requiredCascades(String... requiredCascades)
    {
        this.requiredCascades = requiredCascades;
        return (B)this;
    }
    
    
    /**
     * @param tableName see {@link Table}
     * @return this
     */
    @SuppressWarnings("unchecked")
    public B tableName(String tableName)
    {
        this.tableName = tableName;
        return (B)this;
    }
}
