/* sormula - Simple object relational mapping
 * Copyright (C) 2011-2012 Jeff Miller
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.sormula.builder;

import org.sormula.Database;
import org.sormula.SormulaException;
import org.sormula.Table;


/**
 * Builder for {@link Table} using a fluent style.
 * <p>
 * Example:
 * <blockquote><pre>
Table&lt;SomeTableRow&gt; table = 
    Table.builder(getDatabase(), SomeTableRow.class)
    .autoGeneratedKeys(false)
    .requiredCascades("*")
    .build();
</pre></blockquote>
 *  
 * @author Jeff Miller
 * @since 4.4
 * @param <R> Class associated with a row in table
 */
public class TableBuilder<R> extends AbstractTableBuilder<R, TableBuilder<R>, Table<R>>
{
    public TableBuilder(Database database, Class<R> rowClass) 
    {
        super(database, rowClass);
    }

    
    public Table<R> build() throws SormulaException
    {
        Table<R> table = new Table<R>(database, rowClass);
        init(table);
        return table;
    }
}
