/* sormula - Simple object relational mapping
 * Copyright (C) 2011-2012 Jeff Miller
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.sormula.cache.readwrite;

import java.util.Arrays;

import org.sormula.Database;
import org.sormula.Table;
import org.sormula.Transaction;
import org.sormula.annotation.Column;
import org.sormula.annotation.cache.Cached;
import org.sormula.cache.CacheException;
import org.sormula.cache.CacheKey;
import org.sormula.cache.DuplicateCacheException;
import org.sormula.cache.IllegalCacheOperationException;
import org.sormula.cache.UncommittedRow;
import org.sormula.cache.writable.WritableCache;
import org.sormula.log.ClassLogger;
import org.sormula.operation.InsertOperation;
import org.sormula.operation.ScalarSelectOperation;
import org.sormula.operation.SqlOperation;


/**
 * A cache that retains both selected rows and inserted, updated, and deleted rows. Rows modified with
 * insert, update, and delete are written to the database when transaction is committed. The selected and
 * modified rows are retained cache for life of {@link Database} object or until explicity flushed or evicted.
 * <p>
 * This is a transactional cache which means that caching is performed relative to database transactional
 * boundries of begin, commit, and rollback. Tables that are cached may have no reads/writes unless a transaction 
 * is active. Tables that are cached must use {@link Transaction} obtained from {@link Database#getTransaction()}
 * or must use a subclass of {@link Transaction} that is set with {@link Database#setTransaction(Transaction)}.
 * <p>
 * Caching is stored in map with primary keys as the map key. Primary keys are defined by {@link Column#primaryKey()}.
 * Cache will be searched when selecting by primary key. Non primary key selects will cause cache to write 
 * uncommitted rows to database prior to executing query.
 * 
 * @author Jeff Miller
 * @since 3.0
 *
 * @param <R> row type that is cached
 */
public class ReadWriteCache<R> extends WritableCache<R>
{
    private static final ClassLogger log = new ClassLogger();
    boolean autoGeneratedKeys;
    
    
    public ReadWriteCache(Table<R> table, Cached cachedAnnotation) throws CacheException
    {
        super(table, cachedAnnotation);
    }
    
    
    public void execute(SqlOperation<R> sqlOperation) throws CacheException
    {
        if (sqlOperation instanceof ScalarSelectOperation)
        {
            // select
            if (!sqlOperation.isPrimaryKey())
            {
                // non primary key select
                // must write cache to database prior to select to allow database to include cached rows in select results
                write();
            }
        }
        else if (sqlOperation instanceof InsertOperation)
        {
            // insert
            autoGeneratedKeys = sqlOperation.isAutoGeneratedKeys(); // rows with identity are cached differently
        }
    }


    public void close(SqlOperation<R> sqlOperation) throws CacheException
    {
        // no-op
    }

    
    public R select(Object[] primaryKeys) throws CacheException
    {
        if (log.isDebugEnabled()) log.debug("select() keys=" + Arrays.asList(primaryKeys));
        check();
        R row;
        CacheKey cacheKey = new CacheKey(primaryKeys);
        UncommittedRow<R> uncommittedRow = getUncommitted(cacheKey);
        
        if (uncommittedRow != null)
        {
            // key exists in uncommitted
            if (log.isDebugEnabled()) log.debug("select() from uncommitted cache");
            row = uncommittedRow.select();
        }
        else
        {
            // check committed
            if (log.isDebugEnabled()) log.debug("select() from committed cache");
            row = getCommitted(cacheKey);
        }
        
        if (row != null) hit(); else miss();
        if (log.isDebugEnabled()) log.debug("select() row found = " + (row != null));
        return row;
    }

    
    public boolean insert(R row) throws CacheException
    {
        if (autoGeneratedKeys)
        {
            // always insert rows with auto generated keys so key values are known 
            // immediately instead of when cache writes to database
            return false;
        }
        else
        {
            check();
            CacheKey cacheKey = new CacheKey(getPrimaryKeyValues(row));
            UncommittedRow<R> uncommittedRow = getUncommitted(cacheKey);
            
            if (uncommittedRow != null)
            {
                // key exists in uncommitted
                hit();
                transition(uncommittedRow, uncommittedRow.insert(row));
            }
            else
            {
                // check committed
                if (getCommitted(cacheKey) != null)
                {
                    // row is already in cache, insert will be error
                    hit();
                    throw new DuplicateCacheException(cacheKey.getPrimaryKeys());
                }
                else
                {
                    // row is not in cache, ok to insert
                    miss();
                    putUncommitted(new UncommittedInsert<R>(cacheKey, row));
                }
            }
    
            return true;
        }
    }

    
    public boolean update(R row) throws CacheException
    {
        check();
        CacheKey cacheKey = new CacheKey(getPrimaryKeyValues(row));
        UncommittedRow<R> uncommittedRow = getUncommitted(cacheKey);
        
        if (uncommittedRow != null)
        {
            // key exists in uncommitted
            hit();
            transition(uncommittedRow, uncommittedRow.update(row));
        }
        else
        {
            // row is not in cache, remember update
            miss();
            putUncommitted(new UncommittedUpdate<R>(cacheKey, row));
        }

        return true;
    }

    
    public boolean delete(R row) throws CacheException
    {
        check();
        CacheKey cacheKey = new CacheKey(getPrimaryKeyValues(row));
        UncommittedRow<R> uncommittedRow = getUncommitted(cacheKey);
        
        if (uncommittedRow != null)
        {
            // key exists in uncommitted
            hit();
            transition(uncommittedRow, uncommittedRow.delete(row));
        }
        else
        {
            // row is not in cache, remember delete
            miss();
            putUncommitted(new UncommittedDelete<R>(cacheKey, row));
        }

        return true;
    }

    
    // note if return is null then row is deleted so dont use
    public R selected(R row) throws CacheException
    {
        check();
        R cachedRow;
        CacheKey cacheKey = new CacheKey(getPrimaryKeyValues(row));
        if (log.isDebugEnabled()) log.debug("selected() keys=" + Arrays.asList(cacheKey.getPrimaryKeys()));
        UncommittedRow<R> uncommittedRow = getUncommitted(cacheKey);
        
        if (uncommittedRow != null)
        {
            // key exists in uncommitted
            if (log.isDebugEnabled()) log.debug("selected() from uncommitted cache");
            cachedRow = uncommittedRow.selected(row);
        }
        else
        {
            // check committed
            if (log.isDebugEnabled()) log.debug("selected() from committed cache");
            cachedRow = getCommitted(cacheKey);

            if (cachedRow == null)
            {
                // not in cache yet, new cache entry
                if (log.isDebugEnabled()) log.debug("selected() new uncommitted select");
                putUncommitted(new UncommittedSelect<R>(cacheKey, row));
                cachedRow = row;
            }
        }
        
        return cachedRow;
    }


    public void inserted(R row) throws CacheException
    {
        if (autoGeneratedKeys)
        {
            UncommittedInsert<R> uncommittedInsert = new UncommittedInsert<R>(new CacheKey(getPrimaryKeyValues(row)), row);
            uncommittedInsert.setWritten(true); // already inserted, don't insert again
            putUncommitted(uncommittedInsert);
        }
        else
        {
            // cache inserts all non identity rows 
            // this method should not be invoked for row without identity column
            throw new IllegalCacheOperationException();
        }
    }


    public void updated(R row) throws CacheException
    {
        throw new IllegalCacheOperationException();
    }


    public void deleted(R row) throws CacheException
    {
        throw new IllegalCacheOperationException();
    }
}
